spring:
  sql:
    init:
      mode: always
  profiles:
    default: h2
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: validate
    show-sql: true